### ISSUE TITLE
stopped working?

### ISSUE THREAD

**Issue by trinib** [cosmosis14/custom-youtube#1]
hi is skill still working for you?.. when I search song it don't play.. I changed api key still no luck.. even a other youtube skill don't work.. I guess it's a wide spread thing.. I hope you can assist me..

**Comment by cosmosis14** [comment]
Hello, this was an issue with a ytdl-core update (due to a youtube API update, I presume). I just fixed it today, after testing the newer-version of ytdl-core.

You'll have to update your aws lambda with the new skill.zip (from the latest commit): https://github.com/cosmosis14/custom-youtube/blob/master/dist/skill.zip

Let me know if you're still having issues after that.

**Comment by trinib** [comment]
cool ..i thought it was some module that need fixing ..ill test and let you know

**Comment by trinib** [comment]
working thanks 👍
