### ISSUE TITLE
The invoking the skill, Alexa says "I can't use that on this device"

### ISSUE THREAD

**Issue by NorthernMunkey** [cosmosis14/custom-youtube#2]
Great work btw, 

Normal echo v2 or echo dot,

says i need to got the tv and setting in my alexa app.

assume this is because it knows it's video and not audio? 

audio player is selected in skill, interfaces

**Comment by NorthernMunkey** [comment]
I'm being a muppet, followed your instructions to the end, then didn't look on how you envoke it.
I asked "alexa ask you tube to play green day" and got that response above.
Followed your guide and it works.
would be interesting to understand the difference between the two though?
main reason is most skills you call "alexa ask "skill" to do X
this is the first skill that i have seen where you open the skill up and then control from within it...
nothing wrong with that. will just have to remember to to that... 

thank you for all your hard work.

**Comment by NorthernMunkey** [comment]
SO again looking at your invokes i think it should work ?

"Launch Custom Youtube" or simply "Custom Youtube"   this works... asks for a song and once found it will play

"Ask Custom Youtube to play {Song Name}"   this throws up the error about not being able to open on this device

**Comment by cosmosis14** [comment]
Just to clarify: It sounds like you're getting a generic Alexa error when attempting to play a song from the skill (but only when your first command is to the play song, and not when you launch the skill with no intents and ask for a song after). Is this correct?

I am able to simply say Alexa: "Ask Custom Youtube to play {Song Name}" as the first command (without a prior launch) and it plays with no error. Did you by chance name the skill invocation "youtube" and not "custom youtube"? If that's the case, what might be happening, is Alexa might be responding to your command with an attempt to open some official Youtube app and not Custom Youtube. I remember having some issues during development with that... 

If your problem is something different than that, let me know the exact command you are using, and the error reply you are getting, and I will try to reproduce it.

I've only tested the skill on v2 and v3 echo dots (as that's what I have in the house), but it is working appropriately (most of the time lol) on those.

**Comment by NorthernMunkey** [comment]
yes, you are correct, I put the name as just youtube, changing it, is now allowing it to work.

Many thanks for your work
